-- Create table: users
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY, -- Maps to Supabase Auth User ID if possible, or auto-generated
    email TEXT UNIQUE NOT NULL,
    role TEXT DEFAULT 'pending' CHECK (role IN ('admin', 'user', 'pending')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Note: In a real Supabase Auth integration, you might want to use a trigger to 
-- automatically insert into this table when a new user signs up via Auth.
-- For this app, the Python code handles the insertion logic.

-- Create table: design_docs
CREATE TABLE IF NOT EXISTS design_docs (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name TEXT NOT NULL,
    catalogue TEXT,
    drawing_name TEXT NOT NULL,
    pdf_link TEXT -- URL to the PDF file
);

-- Row Level Security (RLS) is recommended but strictly not requested in the prompt.
-- We will assume the service key or proper client-side handling is used, 
-- but enabling RLS is best practice.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE design_docs ENABLE ROW LEVEL SECURITY;

-- Policy to allow everyone to read design_docs (or restrict to logged in users)
CREATE POLICY "Enable read access for all users" ON design_docs FOR SELECT USING (true);
CREATE POLICY "Enable all access for admins" ON design_docs FOR ALL USING (
  exists (
    select 1 from users where users.id = auth.uid() and users.role = 'admin'
  )
);

-- Policy for users table
CREATE POLICY "Enable read access for own user data" ON users FOR SELECT USING (auth.uid() = id);
-- Admins can read all user data
CREATE POLICY "Enable read access for admins" ON users FOR SELECT USING (
  exists (
    select 1 from users where users.id = auth.uid() and users.role = 'admin'
  )
);
